"""Added settings_msg_id

Revision ID: 7de477a83740
Revises: ddd8f0e2e238
Create Date: 2022-04-11 20:13:03.822239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7de477a83740'
down_revision = 'ddd8f0e2e238'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('preferences', sa.Column('settings_message_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('preferences', 'settings_message_id')
    # ### end Alembic commands ###
